services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3525:3525"
    volumes:
      - ./server:/app